/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gimnasioapp.vistas;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author John Jairo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private JPanel panelContenido;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        setTitle("Sistema de Gestión del Gimnasio");
        setSize(1400, 800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // 🟦 Panel lateral mejorado
        JPanel panelLateral = new JPanel();
        panelLateral.setLayout(new BoxLayout(panelLateral, BoxLayout.Y_AXIS));
        panelLateral.setPreferredSize(new Dimension(200, 0));
        panelLateral.setBorder(BorderFactory.createEmptyBorder(20, 10, 20, 10)); 

        JLabel tituloMenu = new JLabel("Menú");
        tituloMenu.setAlignmentX(Component.CENTER_ALIGNMENT);
        tituloMenu.setFont(new Font("Arial", Font.BOLD, 18));
        tituloMenu.setBorder(BorderFactory.createEmptyBorder(0, 0, 20, 0));

        JButton btnClientes = crearBoton("Clientes");
        JButton btnMembresias = crearBoton("Membresías");
        JButton btnPagos = crearBoton("Pagos");
        JButton btnPlanes = crearBoton("Planes");

        panelLateral.add(tituloMenu);
        panelLateral.add(btnClientes);
        panelLateral.add(Box.createRigidArea(new Dimension(0, 10)));
        panelLateral.add(btnMembresias);
        panelLateral.add(Box.createRigidArea(new Dimension(0, 10)));
        panelLateral.add(btnPagos);
        panelLateral.add(Box.createRigidArea(new Dimension(0, 10)));
        panelLateral.add(btnPlanes);

        panelContenido = new JPanel(new GridBagLayout());

        add(panelLateral, BorderLayout.WEST);
        add(panelContenido, BorderLayout.CENTER);

        // Acciones de los botones
        btnClientes.addActionListener(e -> mostrarVista(new FrmClientes()));
        btnMembresias.addActionListener(e -> mostrarVista(new FrmMembresias()));
        btnPagos.addActionListener(e -> mostrarVista(new FrmPagos()));
        btnPlanes.addActionListener(e -> mostrarVista(new FrmPlanes()));
    }
    
    private void mostrarVista(JPanel vista) {
        panelContenido.removeAll();
        panelContenido.add(vista, new GridBagConstraints());
        panelContenido.revalidate();
        panelContenido.repaint();
    }
    
    private JButton crearBoton(String texto) {
        JButton boton = new JButton(texto);
        boton.setAlignmentX(Component.CENTER_ALIGNMENT);
        boton.setMaximumSize(new Dimension(160, 40));
        return boton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
